### ISSUE TITLE
80 Port not available.

### ISSUE THREAD

**Issue by kanmt** [elleFlorio/svn-docker#1]
Hi, I pull the image, and try to connect to 80 port but failured. And the site (https://medium.com/@elle.florio/the-svn-dockerization-84032e11d88d#.bafh3otmh) I cant open.

run command is : 
docker run -d --name svn-server -p 8091:80 -p 3960:3960 elleflorio/svn-server

And then I try to access 8091 : http://localhost:8091/svn, browser return with message: ERR_CONNECTION_REFUSED

**Comment by kanmt** [comment]
with "curl http://localhost/svn" in the same host, with Error: curl: (56) Recv failure: Connection reset by peer

**Comment by elleFlorio** [comment]
I will look into it ASAP

**Comment by elleFlorio** [comment]
I checked the issue and everything seems to be working (also the link to the medium article).

I ran the command  ```docker run -d --name svn-server -p 8091:80 -p 3960:3960 elleflorio/svn-server``` and I connected to http://localhost:8091/svn without problems.

I think the problem is not related to the container but maybe to your network configuration.

Have a nice day!
