### ISSUE TITLE
Can't open file '/root/.subversion/servers': Permission denied

### ISSUE THREAD

**Issue by hb0730** [elleFlorio/svn-docker#10]
Hello, in the use of your subversion image, report permission issues, is it my configuration error, the following is my screenshot,and attached to my docker-compose.yml
[Enclosure.zip](https://github.com/elleFlorio/svn-docker/files/3365590/Enclosure.zip)

**Comment by elleFlorio** [comment]
Hello hb0730,

I'll check it as soon as possible! It may be related to some permission settings in the docker container. Probably I could solve it using [gosu](https://github.com/tianon/gosu), but I need to read properly how it works 😉
I'll keep you updated!

Thank you

**Comment by elleFlorio** [comment]
Hi @hb0730,

I think I found a solution! The fix is in branch [issue-10](https://github.com/elleFlorio/svn-docker/tree/issue-10). Please give it proper testing and let me know if it is ok! 😉 

Thank you!

**Comment by hb0730** [comment]
Hello @elleforio, according to what you said [issue-10,](https://github.com/elleFlorio/svn-docker/tree/issue-10) I cloned your code, built it into a mirror, started it, created the warehouse, browsed the warehouse, the same error occurred, report permission errors, I want to ask the author whether he tried.

**Comment by elleFlorio** [comment]
Hi,

:thinking: The fixed worked in my quick test. I will try it better and I'll let you know. :smile:

**Comment by elleFlorio** [comment]
Hi @hb0730,

I tried again and it seems working to me. I just did a little modification in the Dockerfile to fix another minor issue.

The steps I followed are the following:
1. build the docker image using the Dockerfile of branch issue-10 using the command:
`docker build -t elleflorio/svn-server .`
2. run your docker-compose file
3. configure the svnadmin settings. Regarding this, I found a misconfiguration in the screenshot you attached. The field "Parent directory of the repositories (SVNParentPath)" should be set to `/home/svn`.
4. login with the default user and create a new repo
5. check the content of the new repo (no error)

Please, try again and let me know if you can make it work! 😉
