### ISSUE TITLE
PHP LDAP extension is not available

### ISSUE THREAD

**Issue by Flo3561** [elleFlorio/svn-docker#11]
I get the following error message (independent of which information is provided in the text input fields):
"PHP LDAP extension is not available".
Is it possible that it is necessary to install php7-ldap as well?
![image](https://user-images.githubusercontent.com/25773748/60882522-6063a980-a248-11e9-91bb-e8e77ca931a0.png)

**Comment by elleFlorio** [comment]
Hi Flo3561,

Thank you for the info, I will try to look into it as soon as I have some time. If you in the meantime can find a solution, feel fry to send a PR! 😉 

Thank you!

**Comment by elleFlorio** [comment]
Hi,
I created a branch [issue-11](https://github.com/elleFlorio/svn-docker/tree/issue-11) with the php7-ldap package in the Dockerfile. Could you test if it can solve your problem?

Thank you! 😄

**Comment by elleFlorio** [comment]
Hi @Flo3561,

I did a quick test and seems working. I'll wait a little more to see if you can do proper testing, then I will merge the fix into the master branch and produce a new image. 😉

**Comment by junstrix** [comment]
Don't forget setting `extension=ldap` in  /etc/php7/php.ini

**Comment by elleFlorio** [comment]
Thank you @junstrix I will do it! ;-)

**Comment by elleFlorio** [comment]
Hey @junstrix, 
I just pushed the change in the branch [issue-11](https://github.com/elleFlorio/svn-docker/tree/issue-11). Can you verify if it is ok? Thank you! 😄

**Comment by elleFlorio** [comment]
Since there are no objections, I merged the modifications in the master branch and update the docker image in Docker Hub. This isssue is closed.
