### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by credel** [elleFlorio/svn-docker#18]
Hi,

im running this config with docker-compose:
subversion:
  image: elleflorio/svn-server
  container_name: subversion
  ports:
    - "81:80"
    - "3690:3690"

i´m adding a user:
docker exec -t subversion htpasswd -b /etc/subversion/passwd admin admin

in brower i can see everything fine:
http://192.168.222.10:81/svn/
Collection of Repositories
Powered by Apache Subversion version 1.12.2 (r1863366).

then i create a repository:
docker exec -t subversion svnadmin create Test

if i try to access the repo in brower:
http://192.168.222.10:81/svn/Test
i´m getting errror that the page is not aviable...
in apache log i can see:
==> /var/log/apache2/access.log <==
192.168.222.175 - admin [23/Nov/2019:13:06:38 +0000] "GET /svn/ HTTP/1.1" 200 254 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
192.168.222.175 - admin [23/Nov/2019:13:06:39 +0000] "GET /svn/ HTTP/1.1" 200 254 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"

==> /var/log/apache2/error.log <==
[Sat Nov 23 13:06:52.403545 2019] [core:notice] [pid 253] AH00051: child pid 270 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:52.403635 2019] [core:notice] [pid 253] AH00051: child pid 271 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:52.403678 2019] [core:notice] [pid 253] AH00051: child pid 272 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:52.403714 2019] [core:notice] [pid 253] AH00051: child pid 273 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:52.403807 2019] [core:notice] [pid 253] AH00051: child pid 274 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:52.403848 2019] [core:notice] [pid 253] AH00051: child pid 275 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:53.406506 2019] [core:notice] [pid 253] AH00051: child pid 291 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:54.411574 2019] [core:notice] [pid 253] AH00051: child pid 292 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:54.411820 2019] [core:notice] [pid 253] AH00051: child pid 293 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:06:55.421070 2019] [core:notice] [pid 253] AH00051: child pid 294 exit signal Segmentation fault (11), possible coredump in /var/www

in /var/www is no coredump....
 
with Tortoise SVN the same:
==> /var/log/apache2/access.log <==
127.0.0.1 - - [23/Nov/2019:13:06:56 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.41 (Unix) SVN/1.12.2 PHP/7.2.24 (internal dummy connection)"
192.168.222.175 - - [23/Nov/2019:13:09:31 +0000] "OPTIONS /svn HTTP/1.1" 401 459 "-" "SVN/1.13.0 (x64-microsoft-windows) serf/1.3.9 TortoiseSVN-1.13.1.28686"
192.168.222.175 - admin [23/Nov/2019:13:09:31 +0000] "OPTIONS /svn HTTP/1.1" 500 606 "-" "SVN/1.13.0 (x64-microsoft-windows) serf/1.3.9 TortoiseSVN-1.13.1.28686"
192.168.222.175 - - [23/Nov/2019:13:09:31 +0000] "OPTIONS / HTTP/1.1" 200 - "-" "SVN/1.13.0 (x64-microsoft-windows) serf/1.3.9 TortoiseSVN-1.13.1.28686"

==> /var/log/apache2/error.log <==
[Sat Nov 23 13:09:31.582530 2019] [core:notice] [pid 253] AH00051: child pid 296 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:31.582606 2019] [core:notice] [pid 253] AH00051: child pid 297 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:31.582637 2019] [core:notice] [pid 253] AH00051: child pid 298 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:31.582664 2019] [core:notice] [pid 253] AH00051: child pid 299 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:31.582693 2019] [core:notice] [pid 253] AH00051: child pid 301 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:31.882931 2019] [dav:error] [pid 304] [client 192.168.222.175:50649] Could not fetch resource information.  [-2, #0]
[Sat Nov 23 13:09:31.882973 2019] [dav:error] [pid 304] [client 192.168.222.175:50649] The URI does not contain the name of a repository.  [405, #190001]
[Sat Nov 23 13:09:32.585564 2019] [core:notice] [pid 253] AH00051: child pid 300 exit signal Segmentation fault (11), possible coredump in /var/www
[Sat Nov 23 13:09:32.585668 2019] [core:notice] [pid 253] AH00051: child pid 302 exit signal Segmentation fault (11), possible coredump in /var/www

what wrong?

**Comment by elleFlorio** [comment]
Hi @credel 
This error again... I will investigate, thank you for reporting! 😉

**Comment by elleFlorio** [comment]
Hi @credel,
Sorry for the long time it took me to get back to you! 🙏 
I don't know if this is still useful but after some unsuccessful investigation I noticed a couple of details in the issue you raised:
- The first one is that probably you are not using the `latest` image I pushed on the Docker Hub. To solve the `Segmentation Fault` issue I had to downgrade the Alpine Linux version to 3.7 (see https://github.com/elleFlorio/svn-docker/issues/12 for details). That version can run only svn version 1.9.7, while in your issue I just noticed that your image is running version 1.12.2. Please run the following command:
```
docker pull elleflorio/svn-server
```
and try again.

- You are creating the folder in the wrong path. You should create it under `/home/svn/`. So the correct command would be:
```
docker exec -t subversion svnadmin create /home/svn/Test
```

Hope this can be helpful, and sorry again for letting you wait so long. 😅
