### ISSUE TITLE
Error: Access to '/svn/Demo/!svn/me' forbidden when commit file

### ISSUE THREAD

**Issue by thangdjw** [elleFlorio/svn-docker#19]
hi elleFlorio
I am trying to set up your image exactly as instructed in the article on medium, but I got this error and I still couldn't find a fix. hope you help me
![image](https://user-images.githubusercontent.com/24998433/71021452-fae9e200-2130-11ea-9e9b-b84ffa99e124.png)

**Comment by xubingtao** [comment]
Me too...The conf like these pictures！So why "Error: Access to '/svn/Demo/!svn/me' forbidden when commit file "????
<img width="389" alt="svnserve" src="https://user-images.githubusercontent.com/6500425/71468422-d365da00-2800-11ea-98e0-00a530460471.png">
<img width="514" alt="authz" src="https://user-images.githubusercontent.com/6500425/71468423-d365da00-2800-11ea-8ae8-9bded00cdc15.png">
<img width="510" alt="passwd" src="https://user-images.githubusercontent.com/6500425/71468425-d4970700-2800-11ea-96e0-cd58bdf4d7db.png">

**Comment by elleFlorio** [comment]
Hello,
Sorry for the late response, sometime I miss some notifications 😅 
I'll give a proper look to find a fix ASAP!

**Comment by xubingtao** [comment]
> Hello,
> Sorry for the late response, sometime I miss some notifications 😅
> I'll give a proper look to find a fix ASAP!

What the fuck! The problem hasn't been solved yet？

**Comment by elleFlorio** [comment]
I work on this thing in my (very limited) free time, and I try to do my best. No need to be rude, man.

Anyway, it sounds like a filesystem permission issue. Try the image tagged with `issue-19` and let me know if it works. 
(it means run it with `docker run -d --name svn-server -p 80:80 -p 3690:3690 elleflorio/svn-server:issue-19`)

**Comment by fangpinchang** [comment]
Hi, @elleFlorio.

Thank you for working on this container.  Unfortunately, I, too, am running into this same commit problem, and your `elleflorio/svn-server:issue-19` image does not fix the problem.

Please take another look.  Thanks!

**Comment by fangpinchang** [comment]
@elleFlorio, I think I know what the problem is.  By default, all users have **_Read only_** permission to all repositories, including the administrator designated per the SVNAdmin UI.

After assigning **_Read & Write_** permissions to suit my needs using SVNAdmin UI, the problem went away.  This is using the `elleflorio/svn-server:latest` image, btw.

**Comment by elleFlorio** [comment]
Thanks @fangpinchang I will then clode the related PR.

**Comment by xubingtao** [comment]
I'm so sorry for my rude @elleFlorio. I know what the problem is, in some Linux environment the /home/svn just had Read only permission.So,I wrote an article on my website to introduce installation methods and problems: https://www.xubingtao.cn/2020/02/07/install_svn

**Comment by reemapal** [comment]
can you give me solution for this regarding
[root@server conf]#  svn import /root/Test/my_repo http://192.168.33.107/svn/Test -m "Initial commit."
svn: E175013: Access to '/svn/Test/!svn/me' forbidden

**Comment by reemapal** [comment]
[root@server conf]#  svn import /root/Test/my_repo http://localhost/svn/Test -m "Initial commit."
svn: E175013: Access to '/svn/Test/!svn/me' forbidden

**Comment by ooing** [comment]
how to do

**Comment by zlshi** [comment]
> vi /etc/subversion/subversion-access-control

It's work

**Comment by keepchen** [comment]
Run this command:
```shell
docker exec -t svn-server sed -i "s/= r/= rw/g" /etc/subversion/subversion-access-control
```  
It will be work fine. 😄 

Thanks to @ooing

**Comment by elleFlorio** [comment]
Thank you for the collaboration! ❤️
