### ISSUE TITLE
Error with user named 'admin'

### ISSUE THREAD

**Issue by lipengin1975** [elleFlorio/svn-docker#25]
Hi, I created a user named 'admin' in iF.SVNAdmin Web page, after that I assign a Access-Path with 'read & write' permission to a exists user (not admin) and 'no permission' to '*', then that user is forbiddened to access the path whith http.
When I tail the /var/log/apache2/error.log, it shows that:
 [authz_svn:error] [pid 281] [client 10.0.16.50:50879] Access denied: 'admin' OPTIONS XXXXXX:/
Finally I delete the 'admin' user, it get fine again.

**Comment by elleFlorio** [comment]
Hello,
Are you using the web interface to assign access-path permissions?
Have you tried with another user different from `admin`?
