### ISSUE TITLE
Strange questions about user permissions

### ISSUE THREAD

**Issue by Personuo** [elleFlorio/svn-docker#26]
To make it easier to configure, I changed the properties of the ```dev_svn.conf file```
```
AuthUserFile /home/svn/passwd
AuthzSVNAccessFile /home/svn/access
```
But when I open``` localhost:port/svn/``` I get an error!

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, add.com@phpstudy and inform them of the time the error occurred, and anything you might have done that may have caused the error
```

I checked the error.log and found errors.
```
AH01620: Could not open password file: /home/svn/passwd
```
Because``` /etc/subversion/passwd ```can be accessed normally.
So I compared the files``` /home/svn/passwd``` and ```/etc/subversion /passwd```
All of their users are``` root:root```

After several attempts, I found that I had to set ```/home/svn/passwd``` to user name ```apache``` in order for the settle

**Comment by elleFlorio** [comment]
Hello,

The issue can be related to the user permission on the filesystem. So you were able to solve this, right?

**Comment by Personuo** [comment]
yes, I solve this problem,thank you for reply!
