### ISSUE TITLE
A question about user rights configuration taking effect in real time

### ISSUE THREAD

**Issue by xushanhuo** [elleFlorio/svn-docker#27]
Hello, I have a question about the permission configuration of the new account. After I add the user account and configure the permissions, the permissions will not be updated in real time. Instead, the permission configuration will take effect by restarting the svn service. I use http Protocol way to use svn, I want to ask if I have not set up the configuration?

**Comment by elleFlorio** [comment]
Hello,

I don't know if that is an issue of svn itself. Have you tried to search if it is an expected behaviour of svn?
