### ISSUE TITLE
line 8: /usr/sbin/apachectl: not found

### ISSUE THREAD

**Issue by Arvingrep** [elleFlorio/svn-docker#29]
there is a problem in follow:

![image](https://user-images.githubusercontent.com/48466044/96543744-9f9bf980-12d7-11eb-86bb-a560c60909ce.png)
![image](https://user-images.githubusercontent.com/48466044/96543789-b80c1400-12d7-11eb-8672-90719e26b11b.png)

**Comment by elleFlorio** [comment]
Hello,

I am not sure, since the docker image I see is not mine. Also, this is based on alpine Linux, so bash is not present.
