### ISSUE TITLE
svnadmin: Error: Could not copy configuration file template

### ISSUE THREAD

**Issue by Basti-Fantasti** [elleFlorio/svn-docker#34]
Hi,

I've set up your docker container using docker-compose on my Synology diskstation.

When I run it and want to access the svnadmin I get the following error message:

```
Error: Could not copy configuration file template. Require write permission (777) to "data" folder and all containing files.
#0 /opt/svnadmin/index.php(20): include_once()
#1 {main}

```

folder and file privileges should be good. Here's my compose file:

![2021-06-11 10_27_46-server1 local - PuTTY](https://user-images.githubusercontent.com/1663072/121656490-d2317700-ca9f-11eb-8d4c-cd5a05e8028e.png)

and here's the directory structure showing the privileges

![2021-06-11 10_27_18-server1 local - PuTTY](https://user-images.githubusercontent.com/1663072/121656540-e07f9300-ca9f-11eb-9277-3ae9e0dd09cd.png)

When starting the container I also found out, that the empty passwd file was missing. It's inside your docker file but it was not created or copied to the configured svn_config dir (./svn_config:/etc/subversion)

I had to manually add it as well as the subversion-access-control file

If you need any further details I'm glad to help!

**Comment by Basti-Fantasti** [comment]
I've digged a bit deeper into it...

in the svnadmin config.inc.php it tries to do the following:

```
// Does the config.ini file exists?
if (!file_exists("./data/config.ini"))
{
  if (!copy("./data/config.tpl.ini", "./data/config.ini"))
    throw new Exception("Could not copy configuration file template. Require write permission (777) to \"data\" folder and all containing files.");
  header("Location: settings.php");
  exit(0);
}

But this source template file is missing


````

**Comment by Basti-Fantasti** [comment]
I manually downloaded the svnadmin release listed in the docker file and copied the .htaccess file and the config.tpl.ini to the data folder and now I see the UI.

I think I can continue from there 😄 

It sometimes help just to note it down somewhere 👍

**Comment by elleFlorio** [comment]
Hey! 😄 
Thank you very much for this, really appreciated! ❤️

**Comment by ted423** [comment]
I think it's maybe need write in Readme, because I had't use svnadmin before
those file a config file and will not be placed in docker
it cause a lot of trouble for first-time users because what they need

**Comment by mkikets99** [comment]
@ted423, i am fully agree with you...
If enyone will wonder how to solve it :
1. Connect `/opt/svnadmin/data` container to any folder
2. Make it `chmod 777` to be sure...
3. Enter that folder and grab files from [github of svn admin](https://github.com/mfreiholz/iF.SVNAdmin/master/data/) (or just simply run this 2 lines)
```bash
wget https://raw.githubusercontent.com/mfreiholz/iF.SVNAdmin/master/data/.htaccess
wget https://raw.githubusercontent.com/mfreiholz/iF.SVNAdmin/master/data/config.tpl.ini
```
