### ISSUE TITLE
apachectl: not found

### ISSUE THREAD

**Issue by calebcbaker** [elleFlorio/svn-docker#35]
I cloned down this repo and attempted to run it via docker-compose but I keep getting the error in the screenshot below. However if I pull the image directly from Docker Hub or build the Dockerfile locally everything works correctly.
![image](https://user-images.githubusercontent.com/8292753/121965682-0375a580-cd33-11eb-9dc3-85b1f1bc3226.png)

docker-compose.yml for reference
![image](https://user-images.githubusercontent.com/8292753/121967672-661c7080-cd36-11eb-9c98-96b38f946e51.png)

**Comment by elleFlorio** [comment]
Hey!

That is weird... 🤔 have you tried to specify the image in the docker compose file?
```    
image: elleflorio/svn-server
```

**Comment by inkdude** [comment]
@calebcbaker Hello!

I change `run` script with this
```
#!/usr/bin/with-contenv sh

exec /usr/sbin/httpd -D FOREGROUND;
```
And all works, please check this

**Comment by elleFlorio** [comment]
@inkdude thank you for your contribution!

I'm closing this since there is no more activity. 😉
