### ISSUE TITLE
Access control via `svn:/`

### ISSUE THREAD

**Issue by sea-kg** [elleFlorio/svn-docker#41]
svnadmin - no have power for configure svn repositories (for protocol `svn://`).

- when I try `svn checkout` repository via `http` - it's ok (server requested login/password)
- when I try `svn checkout` via `svn:/` protocol - it's anytime available for any repository  (no secure)

**Comment by Butler85** [comment]
same with me

**Comment by elleFlorio** [comment]
I am sorry but I could not give this repo the love it deserves. 😞 
So I decided to archive it and make it read only, so people can fork and apply their changes. 

Thank you for taking the time to rise an issue! ❤️
