### ISSUE TITLE
Change timezone possible?

### ISSUE THREAD

**Issue by steffnm** [elleFlorio/svn-docker#43]
Hi, 
I would like to change the timezone, and I tried it per volume and envireoment variable, but nothing worked for me:

docker run (.....)
--volume /etc/localtime:/etc/localtime:ro 
-e "TZ=Europe/Berlin" 

The "date" is always one hour behind my host.

Greetings
Steffen

**Comment by elleFlorio** [comment]
I am sorry but I could not give this repo the love it deserves. 😞 
So I decided to archive it and make it read only, so people can fork and apply their changes. 

Thank you for taking the time to rise an issue! ❤️
