### ISSUE TITLE
solved: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.23.0.2. Set the 'ServerName' directive globally to suppress this message

### ISSUE THREAD

**Issue by zszen** [elleFlorio/svn-docker#44]
modify httpd config：/etc/apache2/httpd.conf

add 
```
ServerName: localhost:80
```

**Comment by georgeslabreche** [comment]
I created a PR to resolve this from the Dockerfile: https://github.com/elleFlorio/svn-docker/pull/46.

**Comment by elleFlorio** [comment]
I am sorry but I could not give this repo the love it deserves. 😞 
So I decided to archive it and make it read only, so people can fork and apply their changes. 

Thank you for taking the time to rise an issue! ❤️
