### ISSUE TITLE
Allow for option to disable WebDAV

### ISSUE THREAD

**Issue by AtelierSnek** [elleFlorio/svn-docker#45]
Hi.

It would be good to be able to disable the webDAV interface if we only want the subversion server to respond to svn:// requests.
Right now, you can just not map 80/443, but apache still commits ~100M of memory, which is not being used in any way if the user isn't using WebDAV.

Ideally, this should be linked to either an environment variable so that it can be set at the CLI (or in a `docker-compose.yml`), or an argument.

Thanks!

**Comment by elleFlorio** [comment]
I am sorry but I could not give this repo the love it deserves. 😞 
So I decided to archive it and make it read only, so people can fork and apply their changes. 

Thank you for taking the time to rise an issue! ❤️
