### ISSUE TITLE
using wrong port for svn

### ISSUE THREAD

**Issue by aleks-mariusz** [elleFlorio/svn-docker#6]
Hi Luca,

I sometimes get dyslexic and reverse the order of things, so i had to double and triple check before i opened this issue, but your [documentation](https://github.com/elleFlorio/svn-docker/blame/master/README.md#L11), [Dockerfile](https://github.com/elleFlorio/svn-docker/blob/master/Dockerfile#L40), etc are referencing port **3960**.  However, the _correct_ port for SVN is 3690.

```
$ grep -E '3(69|96)0' /etc/services
svn             3690/tcp                        # Subversion
svn             3690/udp                        # Subversion
bess            3960/tcp                # Bess Peer Assessment
bess            3960/udp                # Bess Peer Assessment
```

I'm not sure if you meant to obscure the service by writing this backwards or if you suffer from dyslexia occasionally too :-) but this has caused me much confusion when I couldn't get SVN to work connecting to your container :-)

Would you mind if i submit a PR to correct this or is this way for a reason ? If the latter, could you please make a note in your docs so as not to trip other people up like I have been :-)

**Comment by elleFlorio** [comment]
Hey Alex,

oh my, you are right! 😆 
I can confirm it is a case of dyslexia, it was not done intentionally! 😛 
Feel free to submit a PR to make it consistent with the default SVN port. I will then update my Medium story too, to keep them in sync.

Thank you! 😉

**Comment by aleks-mariusz** [comment]
Ahh ok, thanks for the quick reply.  Here's [a PR](https://github.com/elleFlorio/svn-docker/pull/7) fixing this for you..

**Comment by elleFlorio** [comment]
Thank you aleks, sorry for the late merging, is quite a busy period! 😅
