### ISSUE TITLE
The latest Docker image doesn't seem to work

### ISSUE THREAD

**Issue by bvanreeven** [elleFlorio/svn-docker#8]
When I try to run the latest Docker image (image ID `d703d1921c8a`), it doesn't work:

```
$ docker pull elleflorio/svn-server
Using default tag: latest
latest: Pulling from elleflorio/svn-server
Digest: sha256:6b04c01a8c8f9fcf72f0ef2a0de133ee4b82eefae7475ab1f87d740b35f8a2ee
Status: Image is up to date for elleflorio/svn-server:latest
$ docker run elleflorio/svn-server:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying...
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-resolver: executing...
[cont-init.d] 30-resolver: exited 0.
[cont-init.d] 40-resolver: executing...
[cont-init.d] 40-resolver: exited 0.
[cont-init.d] done.
[services.d] starting services
./run: exec: line 5: /usr/sbin/apachectl: not found
[services.d] done.
./run: exec: line 5: /usr/sbin/apachectl: not found
./run: exec: line 5: /usr/sbin/apachectl: not found
./run: exec: line 5: /usr/sbin/apachectl: not found
./run: exec: line 5: /usr/sbin/apachectl: not found
./run: exec: line 5: /usr/sbin/apachectl: not found
^C[cont-finish.d] executing container finish scripts...
```

I compared the files in the Docker image to those in a previous version that does work, and it appears that the file `/usr/sbin/apachectl` is indeed missing compared to the previous version.

I found an issue that looks related: https://github.com/webdevops/Dockerfile/issues/250

The solution appears to be installing the `apache2-ctl` package.

**Comment by bvanreeven** [comment]
For convenience I created a small PR that should fix the issue.

**Comment by anteguitado** [comment]
met the same problem, the latest image is broken with apache-ctl missing.
tried to install apache-ctl manually and httpd is started and the root directory can be successfully accessed from http. But once a repository is created (by svnadmin create rep) and accessed by http, the serving httpd process seg-faults and the browser receives empty response.

**Comment by elleFlorio** [comment]
Oh, sorry guys, probably the latest PR introduced some error. I'll accept the new PR (thank you) and I will check everything as soon as I have some time.

**Comment by bvanreeven** [comment]
@elleFlorio Thanks for publishing the new image! I just verified that it works again for our use case.

Also, thanks for creating this image in the first place! :+1: We have been successfully using it in our Docker-based integration test setup for the past year or so to mock a production SVN server.
